# Generated by Django 6.0.2 on 2026-03-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_group_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('coordinator_forward', 'Coordinator Forwarded Project'), ('presentation_ready', 'Project Ready for Presentation Approval'), ('final_approval', 'Final Project Requires Approval'), ('general', 'General Notification')], default='coordinator_forward', max_length=50),
        ),
    ]
