# Generated by Django 6.0.2 on 2026-04-02 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_literaturereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sddsubmission',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='coordinator1_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='coordinator2_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='guide_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_literature_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='rejection_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='sddsubmission',
            name='coordinator1_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='sddsubmission',
            name='coordinator2_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='sddsubmission',
            name='guide_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='srssubmission',
            name='coordinator1_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='srssubmission',
            name='coordinator2_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='srssubmission',
            name='guide_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('coordinator_forward', 'Coordinator Forwarded Project'), ('presentation_ready', 'Project Ready for Presentation Approval'), ('final_approval', 'Final Project Requires Approval'), ('general', 'General Notification')], default='coordinator_forward', max_length=50),
        ),
        migrations.AlterField(
            model_name='sddsubmission',
            name='sdd_file',
            field=models.FileField(blank=True, null=True, upload_to='sdd_documents/'),
        ),
        migrations.AlterField(
            model_name='sddsubmission',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
