# Generated by Django 6.0.2 on 2026-04-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_sddsubmission_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='coordinator1_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='coordinator2_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='literaturereview',
            name='guide_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sddsubmission',
            name='coordinator1_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sddsubmission',
            name='coordinator2_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sddsubmission',
            name='guide_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='srssubmission',
            name='coordinator1_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='srssubmission',
            name='coordinator2_review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='srssubmission',
            name='guide_review',
            field=models.TextField(blank=True),
        ),
    ]
