# Generated by Django 6.0.2 on 2026-03-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_literaturereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sddsubmission',
            name='rejected_at',
        ),
        migrations.RemoveField(
            model_name='sddsubmission',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='sddsubmission',
            name='rejection_review',
        ),
        migrations.RemoveField(
            model_name='sddsubmission',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='sddsubmission',
            name='sdd_file',
        ),
        migrations.RemoveField(
            model_name='sddsubmission',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='sddsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sdd/'),
        ),
        migrations.AlterField(
            model_name='sddsubmission',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
