# Generated by Django 6.0.2 on 2026-03-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_sddsubmission_rejected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturereview',
            name='guide_approved',
            field=models.BooleanField(default=False),
        ),
    ]
